### ISSUE TITLE
opening curly brace missing in readme

### ISSUE THREAD

**Issue by ohhfine** [nixwiz/sensu-processes-check#1]
sensu-processes-check -s '["search_string": "ssh-agent"}, {"number": 2, "severity": 1, "search_string": "webapp1"}, {"full_cmdline": true, "comparison": "==", "severity": 1, "search_string": "eventmonitor"}]'

are we missing a curly brace here {   sensu-processes-check -s '[ **{**"search_string": "ssh-agent"}

looking forward to trying it out

**Comment by ohhfine** [comment]
same in next example

**Comment by nixwiz** [comment]
Yep, they are missing.  I'll get them fixed soon.

**Comment by nixwiz** [comment]
Closed by 4d6d45b
